import { TrafficConfig } from '../types';

export function generateK6Script(config: TrafficConfig): string {
  const headersObj: Record<string, string> = {};
  config.headers.filter(h => h.enabled && h.key).forEach(h => {
    headersObj[h.key] = h.value;
  });

  return `// k6 Load Test Script generated by TrafficPulse
import http from 'k6/http';
import { check, sleep } from 'k6';

export const options = {
  stages: [
    { duration: '${Math.round(config.loadProfile.rampUpSeconds)}s', target: ${config.loadProfile.targetRps} },
    { duration: '${Math.round(config.loadProfile.durationSeconds - config.loadProfile.rampUpSeconds - config.loadProfile.rampDownSeconds)}s', target: ${config.loadProfile.peakRps || config.loadProfile.targetRps} },
    { duration: '${Math.round(config.loadProfile.rampDownSeconds)}s', target: 0 },
  ],
  thresholds: {
    http_req_duration: ['p(95)<${config.assertions.find(a => a.metric === 'p95_latency')?.threshold || 500}'],
    http_req_failed: ['rate<0.02'],
  },
};

export default function () {
  const url = '${config.targetUrl}';
  const params = {
    headers: ${JSON.stringify(headersObj, null, 4)},
    timeout: '${config.loadProfile.timeoutMs}ms',
  };

  ${config.method === 'GET' || config.method === 'HEAD' ? `
  const res = http.${config.method.toLowerCase()}(url, params);
  check(res, {
    'status is 200': (r) => r.status === 200,
  });
  ` : `
  const payload = JSON.stringify(${config.bodyContent || '{}'});
  const res = http.${config.method.toLowerCase()}(url, payload, params);
  check(res, {
    'status is 2xx': (r) => r.status >= 200 && r.status < 300,
  });
  `}

  sleep(${Math.max(0.1, (1 / (config.loadProfile.targetRps || 10))).toFixed(2)});
}
`;
}

export function generateLocustScript(config: TrafficConfig): string {
  return `# Locust Load Test Script generated by TrafficPulse
import time
from locust import HttpUser, task, between

class TrafficPulseUser(HttpUser):
    wait_time = between(0.1, 0.5)

    @task
    def execute_traffic(self):
        headers = {
${config.headers.filter(h => h.enabled && h.key).map(h => `            "${h.key}": "${h.value}",`).join('\n')}
        }
        ${config.method === 'GET' ? `
        self.client.get(
            "${config.targetUrl}",
            headers=headers,
            name="${config.name}"
        )
        ` : `
        self.client.${config.method.toLowerCase()}(
            "${config.targetUrl}",
            json=${config.bodyContent || '{}'},
            headers=headers,
            name="${config.name}"
        )
        `}
`;
}

export function generateCurlScript(config: TrafficConfig): string {
  const headersList = config.headers
    .filter(h => h.enabled && h.key)
    .map(h => `-H "${h.key}: ${h.value}"`)
    .join(' ');

  const dataFlag = config.bodyType !== 'none' && config.bodyContent ? `-d '${config.bodyContent.replace(/'/g, "\\'")}'` : '';

  return `#!/usr/bin/env bash
# High-Throughput Traffic Generator Loop generated by TrafficPulse
TARGET_URL="${config.targetUrl}"
TOTAL_REQUESTS=${config.loadProfile.targetRps * 10}
CONCURRENCY=${config.loadProfile.concurrencyLimit || 10}

echo "🚀 Dispatching $TOTAL_REQUESTS requests to $TARGET_URL at concurrency $CONCURRENCY..."

seq 1 $TOTAL_REQUESTS | xargs -n 1 -P $CONCURRENCY curl -s -o /dev/null -w "HTTP %{http_code} | Time: %{time_total}s\\n" \\
  -X ${config.method} \\
  ${headersList} \\
  ${dataFlag} \\
  "$TARGET_URL"
`;
}

export function generateAutocannonScript(config: TrafficConfig): string {
  const headersObj: Record<string, string> = {};
  config.headers.filter(h => h.enabled && h.key).forEach(h => {
    headersObj[h.key] = h.value;
  });

  return `// Autocannon Node.js Benchmark Script generated by TrafficPulse
const autocannon = require('autocannon');

async function runBenchmark() {
  const result = await autocannon({
    url: '${config.targetUrl}',
    method: '${config.method}',
    connections: ${config.loadProfile.concurrencyLimit || 10},
    duration: ${config.loadProfile.durationSeconds || 10},
    amount: ${config.loadProfile.targetRps * config.loadProfile.durationSeconds},
    headers: ${JSON.stringify(headersObj, null, 4)},
    ${config.bodyType !== 'none' && config.bodyContent ? `body: JSON.stringify(${config.bodyContent})` : ''}
  });

  console.log(autocannon.printResult(result));
}

runBenchmark();
`;
}
